### ISSUE TITLE
fly execute with multiple --inputs mangles curl progress indicators

### ISSUE THREAD

**Issue by cjcjameson** [concourse/fly#95] opened 2016-06-29 17:54 UTC
When I run fly execute with multiple inputs from my local machine, it tries to report the curl upload progress, but it's mangled. Sometimes it flashes, as if the different progress indicators are overlaying on each other; other times the columns are just all FUBAR.

I'd expect separate sections indicating progress, or a simpler & less informative interface; I don't really care about the progress necessarily.

![screen shot 2016-06-29 at 10 52 01 am](https://cloud.githubusercontent.com/assets/6885889/16462826/e36cdd88-3de7-11e6-9319-ab02ea5c7a21.png)

**Comment by vito** [comment] 2016-10-07 18:18
dupe of https://github.com/concourse/fly/issues/95

**Closed by vito** 2016-10-07 18:18 UTC
Labels: unscheduled
