### ISSUE TITLE
Problems with install instructions on OS X fly binaries

### ISSUE THREAD

**Issue by njbennett** [concourse/fly#219] opened 2018-04-26 04:36 UTC
When I follow the installation instructions under "Installing from the Concourse UI for Project Development" on OS X, I see the following error.
```
○ → fly
-bash: /usr/local/bin/fly: cannot execute binary file
```

Mac also thinks the file is a TextEdit document. It's not obviously the Linux version of the binary-- I downloaded both and they're different sizes.

Could be that there's something odd about the workstation I'm trying this on, but I finally successfully installed with:
```
brew install caskroom/cask/fly
```
so that might be a better instruction for general use.

**Comment by jama-pivotal** [comment] 2018-06-11 15:15
That's a really weird one, going to have the team investigate. Thanks for reporting!

**Comment by cirocosta** [comment] 2018-10-02 14:27
Hey @njbennett ,

<br />

Thanks for submitting the issue!

This problem you face was probably due to the right permission bits not being set (in this case, the `executable` bit).

```sh
# Check out the default permission bits that are set
stat ./fly_darwin_amd64
[...] -rw-r--r-- 1  ...

# Set the executable bit
chmod +x ./fly_darwin_amd64

# Check the new permission bits and verify
# that `x` is now set.
stat ./fly_darwin_amd64
[...] -rwxr-xr-x 1 [...]
```

Regarding `brew`, that's something that is no longer supported (see https://github.com/concourse/homebrew-tap). I'm not aware of reasons though - @vito might be able to provide some more context.

Maybe we could document that? Wdyt @jama-pivotal ?

<br />

Thanks!

**Comment by xtremerui** [comment] 2018-10-02 18:10
The issue is related to concourse/concourse#963. Closing.

**Closed by xtremerui** 2018-10-02 18:10 UTC
Labels: bug, fly, needs-investigation
